import OpenAI from "openai";
import type { FanoutResult, ModelType } from "./types";

let openaiClient: OpenAI | null = null;

function getClient(): OpenAI {
  if (!openaiClient) {
    openaiClient = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }
  return openaiClient;
}

function buildSystemPrompt(modelType: ModelType): string {
  const modelPersonas: Record<ModelType, string> = {
    chatgpt:
      "You simulate ChatGPT/OpenAI's internal query expansion system, which focuses on conversational intent and follow-up questions.",
    perplexity:
      "You simulate Perplexity AI's retrieval system, which emphasizes source diversity, recency, and factual sub-queries.",
    google:
      "You simulate Google AI Mode's query fan-out, which focuses on entity disambiguation, search intent, and SERP feature optimization.",
  };

  return `You are an expert AI search system architect. ${modelPersonas[modelType]}

Your task is to simulate how this AI search system internally expands a single user query into multiple retrieval sub-queries.

Return ONLY valid JSON with no markdown, no code blocks, no extra text. The JSON must follow this exact schema:
{
  "fanout_queries": [
    {
      "query": "string",
      "type": "informational | commercial | comparison | troubleshooting | navigational",
      "intent": "string describing user intent",
      "confidence": number between 0.0 and 1.0
    }
  ]
}`;
}

function buildUserPrompt(query: string, deepMode: boolean): string {
  const count = deepMode ? "25-30" : "12-18";
  return `Given the following user query, simulate how this AI search system would break it into multiple sub-queries for retrieval.

Generate ${count} diverse and realistic search queries that cover:
- Different user intents (informational, commercial, navigational, comparison, troubleshooting)
- Related subtopics and entity variations
- Comparisons with alternatives
- Implicit follow-up questions a user might have
- Commercial and transactional variations
- Time-sensitive variations (2025, 2026, latest, etc.)
- Problem-solving and how-to variants
- Synonym and paraphrase variants

Assign a confidence score (0.0-1.0) based on how likely this sub-query is to be generated by the system.

User query: "${query}"`;
}

export async function generateFanoutWithLLM(
  query: string,
  modelType: ModelType,
  deepMode: boolean
): Promise<FanoutResult> {
  const client = getClient();

  const response = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: buildSystemPrompt(modelType) },
      { role: "user", content: buildUserPrompt(query, deepMode) },
    ],
    temperature: 0.85,
    max_tokens: 3000,
    response_format: { type: "json_object" },
  });

  const content = response.choices[0]?.message?.content;
  if (!content) {
    throw new Error("Empty response from OpenAI");
  }

  let parsed: { fanout_queries: FanoutResult["fanout_queries"] };
  try {
    parsed = JSON.parse(content);
  } catch {
    throw new Error("Failed to parse LLM response as JSON");
  }

  if (!Array.isArray(parsed.fanout_queries)) {
    throw new Error("Invalid response structure from LLM");
  }

  const validated = parsed.fanout_queries
    .filter(
      (q) =>
        q.query &&
        typeof q.query === "string" &&
        q.type &&
        q.intent &&
        typeof q.confidence === "number"
    )
    .map((q) => ({
      query: String(q.query).trim(),
      type: (["informational", "commercial", "comparison", "troubleshooting", "navigational"].includes(q.type)
        ? q.type
        : "informational") as FanoutResult["fanout_queries"][0]["type"],
      intent: String(q.intent).trim(),
      confidence: Math.min(1, Math.max(0, Number(q.confidence))),
    }));

  return {
    original_query: query,
    fanout_queries: validated,
    model_type: modelType,
    generated_at: new Date().toISOString(),
    total_count: validated.length,
    is_mock: false,
  };
}

export function hasApiKey(): boolean {
  return Boolean(process.env.OPENAI_API_KEY?.trim());
}
