import OpenAI from "openai";
import type { FanoutResult, ModelType } from "./types";

let openaiClient: OpenAI | null = null;

function getClient(): OpenAI {
  if (!openaiClient) {
    openaiClient = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }
  return openaiClient;
}

function buildSystemPrompt(modelType: ModelType): string {
  const modelPersonas: Record<ModelType, string> = {
    chatgpt:
      "You simulate ChatGPT/OpenAI's internal query expansion system. Focus on conversational intent, follow-up questions a real user would ask, and natural language variations of the original query.",
    perplexity:
      "You simulate Perplexity AI's retrieval system. Focus on factual sub-queries, source diversity, recent information needs, and breaking the query into specific answerable questions.",
    google:
      "You simulate Google AI Mode's query fan-out. Focus on entity disambiguation, search intent classification, SERP feature optimization, and queries that match real Google search patterns.",
  };

  return `You are an expert SEO and AI search system specialist. ${modelPersonas[modelType]}

Your task is to generate realistic search sub-queries that a real person would actually type into a search engine when researching the given topic.

STRICT RULES:
- Every query must be something a real user would genuinely search for
- Queries must be directly related to the original topic — do NOT invent unrelated topics
- Use natural search language (how people actually type queries)
- Do NOT add fictional brands, made-up products, or non-existent services
- Keep queries concise and realistic (2-8 words typically)

Return ONLY valid JSON with no markdown, no code blocks, no extra text. Use this exact schema:
{
  "fanout_queries": [
    {
      "query": "string",
      "type": "informational | commercial | comparison | troubleshooting | navigational",
      "intent": "one sentence describing what the user wants to find",
      "confidence": number between 0.0 and 1.0
    }
  ]
}`;
}

function extractKeywords(query: string): string[] {
  const stopwords = new Set([
    "the",
    "a",
    "an",
    "and",
    "or",
    "to",
    "for",
    "of",
    "in",
    "on",
    "with",
    "best",
    "cheap",
    "how",
    "what",
    "why",
    "when",
    "vs",
    "versus",
    "compare",
    "comparison",
    "troubleshooting",
    "error",
    "fix",
    "login",
    "official",
    "site",
    "service",
    "software",
    "tool",
    "tools",
    "generator",
    "mode",
    "ai",
  ]);

  const normalized = query
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  const tokens = normalized
    .split(" ")
    .filter((t) => t.length >= 3 && !stopwords.has(t));

  const unique = Array.from(new Set(tokens));
  return unique.slice(0, 8);
}

function buildUserPrompt({
  query,
  deepMode,
  keywords,
  strictKeywordEnforcement,
}: {
  query: string;
  deepMode: boolean;
  keywords: string[];
  strictKeywordEnforcement: boolean;
}): string {
  const targetCount = deepMode ? 30 : 14;
  const keywordText = keywords.length > 0 ? keywords.join(", ") : "N/A";

  return `Generate exactly ${targetCount} realistic, semantically diverse search sub-queries for the following user query.

Anti-hallucination rules:
- Do not invent unrelated topics.
- Stay strictly on topic.

Keyword enforcement:
- Keywords extracted from the original query: ${keywordText}
${strictKeywordEnforcement ? "- STRICT: each sub-query must include at least one keyword (case-insensitive substring match)." : "- Prefer including at least one keyword in each sub-query when possible."}

Each sub-query must:
1. Be something a real person would actually search for on Google/ChatGPT/Perplexity
2. Cover different angles across the set: informational, commercial, comparison, troubleshooting, navigational
3. Use natural search language
4. Be concise (typically 2-8 words)

Bad examples (too vague or unrelated):
- "business productivity tools"
- "software solutions for enterprises"

Assign confidence (0.0-1.0) based on how likely this exact sub-query would be generated by the system.

User query: "${query}"`;
}

export async function generateFanoutWithLLM(
  query: string,
  modelType: ModelType,
  deepMode: boolean
): Promise<FanoutResult> {
  const client = getClient();

  const keywords = extractKeywords(query);
  const targetCount = deepMode ? 30 : 14;

  const attempts: { temperature: number; strictKeywordEnforcement: boolean }[] = [
    { temperature: 0.25, strictKeywordEnforcement: false },
    { temperature: 0.15, strictKeywordEnforcement: true },
  ];

  let lastError: unknown = null;
  let bestFanout: FanoutResult["fanout_queries"] = [];

  const normalizedKeywordSet = new Set(
    keywords.map((k) => k.toLowerCase()).filter(Boolean)
  );

  for (const attempt of attempts) {
    try {
      const response = await client.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: buildSystemPrompt(modelType) },
          {
            role: "user",
            content: buildUserPrompt({
              query,
              deepMode,
              keywords,
              strictKeywordEnforcement: attempt.strictKeywordEnforcement,
            }),
          },
        ],
        temperature: attempt.temperature,
        top_p: 0.9,
        max_tokens: 2400,
        presence_penalty: 0.0,
        frequency_penalty: 0.2,
        response_format: { type: "json_object" },
      });

      const content = response.choices[0]?.message?.content;
      if (!content) throw new Error("Empty response from OpenAI");

      let parsed: { fanout_queries: FanoutResult["fanout_queries"] };
      try {
        parsed = JSON.parse(content);
      } catch {
        throw new Error("Failed to parse LLM response as JSON");
      }

      if (!Array.isArray(parsed.fanout_queries)) {
        throw new Error("Invalid response structure from LLM");
      }

      const rawValidated = parsed.fanout_queries
        .filter(
          (q) =>
            q.query &&
            typeof q.query === "string" &&
            q.type &&
            q.intent &&
            typeof q.confidence === "number"
        )
        .map((q) => {
          const cleanQuery = String(q.query).trim();
          const wordCount = cleanQuery.split(/\s+/).filter(Boolean).length;
          const cleanLower = cleanQuery.toLowerCase().replace(/\s+/g, " ").trim();
          const typeCandidate = String(q.type).trim();

          return {
            query: cleanQuery,
            normalizedLower: cleanLower,
            wordCount,
            type: ([
              "informational",
              "commercial",
              "comparison",
              "troubleshooting",
              "navigational",
            ].includes(typeCandidate)
              ? typeCandidate
              : "informational") as FanoutResult["fanout_queries"][0]["type"],
            intent: String(q.intent).trim(),
            confidence: Math.min(1, Math.max(0, Number(q.confidence))),
          };
        })
        .filter((q) => q.wordCount >= 2 && q.wordCount <= 12);

      // De-dupe while preserving first occurrence.
      const seen = new Set<string>();
      const deduped = rawValidated.filter((q) => {
        if (seen.has(q.normalizedLower)) return false;
        seen.add(q.normalizedLower);
        return true;
      });

      // Anti-hallucination keyword filter (when keywords exist).
      const filtered = deduped.filter((q) => {
        if (normalizedKeywordSet.size === 0) return true;
        const qLower = q.query.toLowerCase();
        for (const k of Array.from(normalizedKeywordSet)) {
          if (qLower.includes(k)) return true;
        }
        return false;
      });

      const sliced = filtered.slice(0, targetCount).map((q) => ({
        query: q.query,
        type: q.type,
        intent: q.intent,
        confidence: q.confidence,
      }));

      if (sliced.length > bestFanout.length) bestFanout = sliced;

      // If we got close to target, accept.
      if (sliced.length >= Math.floor(targetCount * 0.75)) {
        break;
      }
    } catch (err) {
      lastError = err;
    }
  }

  if (bestFanout.length === 0) {
    const msg =
      lastError instanceof Error ? lastError.message : "Failed to generate fan-out queries.";
    throw new Error(msg);
  }

  return {
    original_query: query,
    fanout_queries: bestFanout,
    model_type: modelType,
    generated_at: new Date().toISOString(),
    total_count: bestFanout.length,
    is_mock: false,
  };
}

export function hasApiKey(): boolean {
  return Boolean(process.env.OPENAI_API_KEY?.trim());
}
